server:
  port: 8081
spring:
  application:
    name: gts-manage-education
  #profiles: # 环境设置：dev、test、prod
  # active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/gootschool?useSSL=true&serverTimezone=UTC
    username: root
    password: admin
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka


mybatis-plus: #打印 SQL 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

